//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PeachOCR.Properties {


    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.0.3.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {

        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

        public static Settings Default {
            get {
                return defaultInstance;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("OpenAI兼容")]
        public string AIServiceProvider {
            get {
                return ((string)(this["AIServiceProvider"]));
            }
            set {
                this["AIServiceProvider"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.openai.com/v1")]
        public string AIApiUrl {
            get {
                return ((string)(this["AIApiUrl"]));
            }
            set {
                this["AIApiUrl"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AIApiKey {
            get {
                return ((string)(this["AIApiKey"]));
            }
            set {
                this["AIApiKey"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("gpt-3.5-turbo")]
        public string AIModelName {
            get {
                return ((string)(this["AIModelName"]));
            }
            set {
                this["AIModelName"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("请对以下OCR识别结果进行文本增强优化，要求：\n1. 保持原文语言不变（中文保持中文，英文保持英文，不进行翻译）\n2. 纠正错别字、OCR识别错误和明显的拼写错误\n3. 优化文本排版：规范标点符号使用，修正空格和换行\n4. 根据语义进行合理的段落划分：按内容逻辑分段，保持段落连贯性\n5. 保持原文意思和专业术语不变\n6. 只返回优化后的文本内容，不要添加任何解释或说明\n\nOCR识别结果：")]
        public string AIOcrEnhancementPrompt {
            get {
                return ((string)(this["AIOcrEnhancementPrompt"]));
            }
            set {
                this["AIOcrEnhancementPrompt"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("请对以下文本进行分析和总结：\n1. 提取关键信息\n2. 总结主要内容\n3. 识别重要数据或要点\n4. 以清晰的结构呈现\n\n需要分析的文本：")]
        public string AIAnalysisPrompt {
            get {
                return ((string)(this["AIAnalysisPrompt"]));
            }
            set {
                this["AIAnalysisPrompt"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("请将以下文本翻译成中文：\n1. 保持专业术语的准确性\n2. 确保翻译的流畅性和可读性\n3. 保持原文的格式和结构\n\n需要翻译的文本：")]
        public string AITranslationPrompt {
            get {
                return ((string)(this["AITranslationPrompt"]));
            }
            set {
                this["AITranslationPrompt"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("txt标准格式")]
        public string AIOutputFileFormat {
            get {
                return ((string)(this["AIOutputFileFormat"]));
            }
            set {
                this["AIOutputFileFormat"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PaddleOCR（在线）")]
        public string OCRServiceProvider {
            get {
                return ((string)(this["OCRServiceProvider"]));
            }
            set {
                this["OCRServiceProvider"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://paddleocr.aistudio-app.com/api/v2/ocr/jobs")]
        public string OCRApiUrl {
            get {
                return ((string)(this["OCRApiUrl"]));
            }
            set {
                this["OCRApiUrl"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OCRApiKey {
            get {
                return ((string)(this["OCRApiKey"]));
            }
            set {
                this["OCRApiKey"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PaddleOCR-VL-1.5")]
        public string OCRModel {
            get {
                return ((string)(this["OCRModel"]));
            }
            set {
                this["OCRModel"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ScreenshotHotkey {
            get {
                return ((string)(this["ScreenshotHotkey"]));
            }
            set {
                this["ScreenshotHotkey"] = value;
            }
        }
    }
}